version: "3.8"

services: 
  adminer:
    image: olv04:5000/adminer:4.8.1
    networks:
      - postgres
    ports:
      - 8083:8080
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.labels.worker==yes"

networks:
  postgres:
    external: true