version: '3.3'

services:
  typebot-db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - /mnt/typebot-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot

  typebot-builder:
    image: baptistearno/typebot-builder:2.28.2
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env

  typebot-viewer:
    image: baptistearno/typebot-viewer:2.28.2
    restart: always
    ports:
      - '8081:3000'
    env_file: .env