version: '3.3'

services:
  typebot-db:
    image: postgres:14-alpine
    volumes:
      - /mnt/typebot-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==olv01"
    
  typebot-builder:
    image: baptistearno/typebot-builder:2.28.2
    depends_on:
      - typebot-db
    ports:
      - '8080:3000'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.labels.worker==yes"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    #env_file: stack.env

  typebot-viewer:
    image: baptistearno/typebot-viewer:2.28.2
    ports:
      - '8081:3000'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.labels.worker==yes"
    #env_file: stack.env