version: '3.8'

services:
  typebot-builder:
    image: baptistearno/typebot-builder:2.28.2
    networks:
      - appsnet
    depends_on:
      - postgres
    ports:
      - '8080:3000'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.labels.worker==yes"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      NODE_OPTIONS: ${NODE_OPTIONS}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXT_PUBLIC_VIEWER_URL: ${NEXT_PUBLIC_VIEWER_URL}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      NEXT_PUBLIC_SMTP_FROM: ${NEXT_PUBLIC_SMTP_FROM}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_AUTH_DISABLE: ${SMTP_AUTH_DISABLE}
      DISABLE_SIGNUP: ${DISABLE_SIGNUP}

  typebot-viewer:
    image: baptistearno/typebot-viewer:2.28.2
    networks:
      - appsnet
    ports:
      - '8081:3000'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.labels.worker==yes"
    environment:
      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      NODE_OPTIONS: ${NODE_OPTIONS}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXT_PUBLIC_VIEWER_URL: ${NEXT_PUBLIC_VIEWER_URL}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      NEXT_PUBLIC_SMTP_FROM: ${NEXT_PUBLIC_SMTP_FROM}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_AUTH_DISABLE: ${SMTP_AUTH_DISABLE}
      DISABLE_SIGNUP: ${DISABLE_SIGNUP}

networks:
  appsnet:
    external: true