version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /homer/oliver/portainer_data:/data
    restart: always
    ports:
      - 9000:9000
      - 9443:9443
    networks:
      - my-net

networks:
  my-net:
    external: true