version: "3.9"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    networks:
      - my-net2
    volumes:
      - /mnt/uptime-kuma:/app/data
    ports:
        - 8084:3001
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==worker"

networks:
  my-net2:
    external: true