version: "3.9"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    #networks:
    #  - npm_default
    volumes:
      - /dados/uptime-kuma:/app/data
    ports:
        - 3001:3001
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.labels.worker==yes"

#networks:
#  npm_default:
#    external: true