version: "3.9"

services:
  visualizer:
      image: alexellis2/visualizer-arm:latest
      ports:
        - 8082:8080
      stop_grace_period: 1m30s
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
        placement:
          constraints:
            - "node.hostname==olv01"
