version: '3.8'

services:
  redis:
    image: olv04:5000/redis:7-alpine
    networks:
      - redis
      - appsnet
    volumes:
      - /mnt/redis:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.labels.worker==yes"

networks:
  redis:
    external: true
  appsnet:
    external: true